version: "3.8"

services:
  sonarqube:
    image: sonarqube:25.11.0.114957-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - ./plugins:/opt/sonarqube/extensions/plugins
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_logs:
